# TODO: Change these to functions that assemble based on unique values already input (once enough entered (at least for passengers))

aircraftIDs = ['Simulation',
               'N908JE',
               'N909JE',
               'N908GM',
               'N739SP',
               'N474AW',
               'N909JG',
               'N407BP',
               'N491GM',
               'N5279X',
               'N500JA',
               'N16909',
               'N125MF',
               'N72PH',
               'N505LS',
               'N75RR',
               'N778ME',
               'N4424E',
               'N307BG',
               'Other']

aircraftMakes = ['Gulfstream',
                 'Boeing',
                 'Other']

aircraftModels = ['727-200', '727-31', '727-31H',
                  '1159B', '421B', '206-L3', 'BHT-407', 'Other']

origs_dests = ['ABY',
               'ABQ',
               'AEG',
               'ASE',
               'BED',
               'BGR',
               'BOS',
               'CMH',
               'CYQX',
               'CYUL',
               'DGAA',
               'DNAA',
               'EGBB',
               'EGGW',
               'EIDW',
               'EINN',
               'ESSA',
               'EWR',
               'FACT',
               'FAJS',
               'FQMA',
               'GMME',
               'GMTT',
               'GVAC',
               'HPN',
               'HRYR',
               'HVN',
               'IAD',
               'JAX',
               'JFK',
               'LCL',
               'LEGR',
               'LFPB',
               'LFTH',
               'LFMN',
               'LGMO',
               'LIML',
               'LGA',
               'LKPR',
               'LNA',
               'LPAZ',
               'MBPV',
               'MDW',
               'MIA',
               'MIV',
               'MPPV',
               'MRY',
               'MTN',
               'MVY',
               'MYEF',
               'MYNN',
               'OMDB',
               'PANC',
               'PBI',
               'RJTA',
               'SAN',
               'SBGR',
               'TEB',
               'TGB',
               'TIST',
               'UUWW',
               'VCBI',
               'VHHH',
               'VNNT',
               'VNY',
               'VTBD',
               'WBSB',
               'WRRR',
               'WSSS',
               'WTBD',
               'ZBAA',
               'ZGSZ',
               'Other']

neo4j_import_dir = r"C:\Users\Tundra\.Neo4jDesktop\neo4jDatabases\database-8f33f594-a792-462c-8692-44868aa82820\installation-3.5.6\import"
